name: Trigger Vercel Redeploy

on:
  push:
    branches:
      - main

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel hook
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_U96HCdeSde3vV0mHwiz8PmvnE3bY/vqbdE867gk
