# .github/workflows/trigger-deploy.yml
name: Trigger Website Update
on:
  push:
    branches: [ main ]
  
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger website redeploy
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          https://api.github.com/repos/lolidrk/bragging-rights-website/dispatches \
          -d '{"event_type":"log-update"}'
